### ISSUE TITLE
Potassium and Calcium not displaying correct results

### ISSUE THREAD

**Issue by macsrok** [nutritionix/nutrition-label#115]
I'm developing a feature for our rails app that uses this plug-in. I have noticed no matter what value is passed into `valuePotassium_2018` and  `valueCalcium` the rendered output doesn't match. I have provided my configuration hash below, as well as an image showing the rendered label. 

`{"valueServingWeightGrams":186.99,"valueCalories":383.77,"valueTotalFat":30.17,"valueSatFat":11.33,"valueTransFat":0.01,"valueCholesterol":93.0,"valueSodium":273.33,"valueTotalCarb":21.21,"valueFibers":7.9,"valueSugars":9.75,"valueAddedSugars":4.34,"valueProteins":11.44,"valueVitaminD":0.5,"valueCalcium":25.0,"valueIron":2.59,"valuePotassium_2018":2.1,"width":300,"showServingUnitQuantity":true,"itemName":"Almond Flour Pancakes with Strawberry Chia Seed Jam","decimalPlacesForQuantityTextbox":2,"allowFDARounding":false,"decimalPlacesForNutrition":2,"showPolyFat":false,"showMonoFat":false,"showLegacyVersion":false,"showServingUnitQuantityTextbox":false,"valueServingUnitQuantity":6,"valueServingSizeUnit":"","ingredientList":"","hidePercentDailyValues":true,"showCustomFooter":false,"valueCustomFooter":""}`

![Screenshot from 2019-06-12 12-07-50](https://user-images.githubusercontent.com/1218215/59362993-d5f05e80-8d0a-11e9-820d-53eef86a79ba.png)

**Comment by majin22** [comment]
@macsrok the value is the percentage which is hidden on your label https://github.com/nutritionix/nutrition-label/wiki/Difference-Between-the-Legacy-and-the-2018-Label

what you are seeing is the base value that is computed based on the percentage of calcium and potassium https://github.com/nutritionix/nutrition-label/wiki/How-the-Percent-Daily-Value-is-Computed

hope this clear things up

thanks

**Comment by macsrok** [comment]
So `valueCalcium` is a % of daily value and not the value like everything else?

**Comment by majin22** [comment]
yes but it is not the only one. this also applies to vit a, vit c, vit d, calcium, iron and potassium (for 2018)

**Comment by majin22** [comment]
check the demo http://dev2.nutritionix.com/html/label-jquery-plugin/demo/demo.html
