### ISSUE TITLE
JQuery not defined Error

### ISSUE THREAD

**Issue by meallogixreid** [nutritionix/nutrition-label#133]
When attempting to import the library into my react app I get a jQuery not defined error. I have not changed any of the plugin code.

<img width="1457" alt="Screen Shot 2021-01-21 at 10 03 51 AM" src="https://user-images.githubusercontent.com/74558028/105393687-8c6d3280-5c14-11eb-88ba-771a933eb86c.png">

<img width="1792" alt="Screen Shot 2021-01-21 at 10 04 13 AM" src="https://user-images.githubusercontent.com/74558028/105393560-66479280-5c14-11eb-9c23-dc6094474fe4.png">

**Comment by majin22** [comment]
@meallogixreid sorry for the late reply. I am not familiar with reactJs but the only explanation I can think of is that you didn't include jquery or your code doesn't recognize the jquery that you included. thanks
