### ISSUE TITLE
Divide by zero issue (NaN) for some daily values

### ISSUE THREAD

**Issue by mdg357** [nutritionix/nutrition-label#39]
It is possible that calculating the daily values may lead to a "NaN" being displayed to the user.

For exampe, if dailyValueSodium == 0, then the following code will produce a "NaN" on screen:

```javascript
($this.settings.allowFDARounding ? roundPotassiumRule($this.settings.valuePotassium) : $this.settings.valuePotassium) / ($this.settings.dailyValuePotassium * calorieIntakeMod)
```

**Comment by majin22** [comment]
@mdg357 I am very sorry I missed this commit. I will review it and merge it later

also tagging @mattsilv to keep him informed
