### ISSUE TITLE
css issue with labels where the item name is long

### ISSUE THREAD

**Issue by majin22** [nutritionix/nutrition-label#44]
@genesis23rd I found this today by accident

http://dev2.nutritionix.com/html/label-jquery-plugin/demo/demo-long-item-name.html

there is a js error `Uncaught Error: Syntax error, unrecognized expression: # test4 .name.inline` but I think this css line might be linked to it https://github.com/nutritionix/nutrition-label/blob/master/nutritionLabel.css#L67-L70

can you check this out

thanks

**Comment by genesis23rd** [comment]
This was a js issue. Fixed via https://github.com/nutritionix/nutrition-label/commit/f9f4e4cd6211025c75491df06beddb3b0d35d555

**Comment by majin22** [comment]
verified fixed
