### ISSUE TITLE
ReferenceError: x is not defined

### ISSUE THREAD

**Issue by rigobcastro** [nutritionix/nutrition-label#58]
Hi, I have this problem when I'm trying to use it.

![captura de pantalla 2017-01-04 a las 8 27 02 a m](https://cloud.githubusercontent.com/assets/1006483/21643672/9e79f62a-d257-11e6-93db-3c704d9e3839.png)

My code

`<div id="test"></div>`
`$('#test').nutritionLabel();`

Thanks for your support!

**Comment by majin22** [comment]
@rigobcastro sorry I missed this as I didn't an email notification of this issue. I'll try and reply asap

**Comment by majin22** [comment]
@rigobcastro I can't really be sure of what's the problem as that is really the most basic use of the plugin

did you include the jquery library that is needed by the plugin?

it is best to try the not minified version `nutritionLabel.js` so I can see on what exact line the error occurred

thanks

http://dev2.nutritionix.com/html/label-jquery-plugin/demo/demo.html
