### ISSUE TITLE
add new fields to the plugin

### ISSUE THREAD

**Issue by majin22** [nutritionix/nutrition-label#59]
related to https://github.com/mattsilvllc/Nutritionix-Yii/issues/2524

update the plugin to support the new fields mentioned here https://github.com/mattsilvllc/Nutritionix-Yii/wiki/New-Nutrition-Fact-Attributes-added-in-2017

**Comment by Yurko-Fedoriv** [comment]
@majin22 please ping me when done, so I can make needed adjustments here https://github.com/mattsilvllc/NewSiteDesign/issues/1302

**Comment by majin22** [comment]
@mattsilv do we still need to have a `unit quantity textbox` that will change the data of the label when the value there is updated?

**Comment by mattsilv** [comment]
@majin22 Yes, that will still be the same input box and that same value still appears on the new label, just in a slightly different layout

**Comment by Yurko-Fedoriv** [comment]
@majin22 FYI here is a new template @genesis23rd developed http://dev2.nutritionix.com/html/label/v3/nutrition-label.html

**Comment by majin22** [comment]
@Yurko-Fedoriv I am starting to work on this. there were just other tasks that I needed to prioritize. thanks

**Comment by majin22** [comment]
@mattsilv am I correct to assume that `2/3` will be the textbox https://github.com/mattsilvllc/Nutritionix-Yii/wiki/New-Nutrition-Fact-Attributes-added-in-2017?

thanks

**Comment by majin22** [comment]
@genesis23rd I modified the template so they will have a pattern so I can use 1 function to render most elements http://dev2.nutritionix.com/html/label/v3/nutrition-label.html. thanks

**Comment by majin22** [comment]
## suggestion 1

@mattsilv and @genesis23rd I suggest we change the design at the bottom to be like the legacy label as currently it is cramped http://www.nutritionix.com/html/label/v3/nutrition-label.html

the 2018 label here have a different format than the one on the wiki https://www.fda.gov/Food/GuidanceRegulation/GuidanceDocumentsRegulatoryInformation/LabelingNutrition/ucm385663.htm#images

what do you think about this?

thanks

**Comment by majin22** [comment]
## question 2

@mattsilv I am not sure on how to calculate the percent value for added sugar as I didn't see it's daily value here https://www.fda.gov/Food/GuidanceRegulation/GuidanceDocumentsRegulatoryInformation/LabelingNutrition/ucm064928.htm

any advice?

thanks

**Comment by majin22** [comment]
## question 3

am I correct to assume that I will use the same rounding rule for `added sugar` and `sugar`?

thanks

**Comment by majin22** [comment]
## question 4

@mattsilv on the 2018 version, is it normal that we won't have `menu item` or `modifier name`?

also, `fat calories` or `calories from fat` seems to be omitted, is this correct https://www.fda.gov/Food/GuidanceRegulation/GuidanceDocumentsRegulatoryInformation/LabelingNutrition/ucm385663.htm#images?

thanks

**Comment by majin22** [comment]
@genesis23rd can you improve the design of the 2018 label.

after you pulled the latest file, compare the pages `http://localhost/mattsilv/nutrition-label/demo/demo.html` and `http://localhost/mattsilv/nutrition-label/demo/demo-2018.html` (similar data to the `demo.html` version so you can use this to compare the legacy and 2018 label versions). Just change the path with your local version

you need to update the file `nutritionLabel.css` and both of those html pages uses this version and not the minimized version (i'll change it later when we are done with all the needed changes)

let me know if you need any assistance or if you need some html code changed

thanks

**Comment by genesis23rd** [comment]
@majin22 I'm done with style changes.

**Comment by majin22** [comment]
@genesis23rd thanks

@mattsilv I will need feedback from you on my queries before I can proceed on this task.

Thanks

**Comment by majin22** [comment]
## question 5

@mattsilv here is the current look of the 2018 version compared to the legacy version. Please let us know if you want to change the style of the 2018 version especially the width and the this one https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-280907585

Thanks

![label_legacy](https://cloud.githubusercontent.com/assets/271582/23167267/acd054a6-f87e-11e6-9272-863b31db640a.png)

![label-2018](https://cloud.githubusercontent.com/assets/271582/23167268/acd2f62a-f87e-11e6-86dc-a749c6698371.png)

**Comment by mattsilv** [comment]
@majin22 let's remove this table at the bottom for now, as I do not believe that is required
![add new fields to the plugin issue 59 nutritionix nutrition-label 2017-02-21 10-23-04](https://cloud.githubusercontent.com/assets/156176/23171197/d3722774-f81f-11e6-9b28-e54d83c9e565.png)

**Comment by majin22** [comment]
@mattsilv noted. I also want to follow these:

1. question 1 https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-280875739

2. suggestion 1 (your feedback on this suggestion) https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-280907585

3. question 2 https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-280910314

4. question 3 https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-280944880

5. question 4 https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-281071076

thanks

**Comment by mattsilv** [comment]
@majin22 

1.  
> I correct to assume that 2/3 will be the textbox https://github.com/mattsilvllc/Nutritionix-Yii/wiki/New-Nutrition-Fact-Attributes-added-in-2017

I am not following this question.. Which textbox and what is "2/3" related to?

2.  Agree

3.  % value added sugar appears to be based on 100g added sugar per day.  Will confirm with Paige.

4.  Correct, same rounding rule for sugar and added sugar.

5.  We will keep the menu item and modifer name in the label for our since it is necessary for our interfaces to describe what the items are.  That should be added.

**Comment by majin22** [comment]
@mattsilv about `2/3`, i'll reply later when I can upload the demo page so I can demonstrate it better. Thanks

**Comment by majin22** [comment]
@genesis23rd can you change the bottom nutrition as Matt approved this suggestion http://dev2.nutritionix.com/html/label/v3/nutrition-label.html https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-280907585. thanks

**Comment by majin22** [comment]
@genesis23rd you also need to added a way to display the menu item and modifier names

> We will keep the menu item and modifer name in the label for our since it is necessary for our interfaces to describe what the items are. That should be added.

thanks

**Comment by genesis23rd** [comment]
@majin22 @mattsilv http://dev2.nutritionix.com/html/label/v3/nutrition-label.html
Let me know your thoughts.

**Comment by majin22** [comment]
@genesis23rd looks great. thanks

**Comment by majin22** [comment]
@mattsilv @Yurko-Fedoriv and @genesis23rd I just want to let you know that for the `textbox / arrows` and `data name`, I will apply the same logic that we are applying before https://github.com/nutritionix/nutrition-label/blob/master/index.html#L100-L123

**Comment by mattsilv** [comment]
sounds good

**Comment by majin22** [comment]
@genesis23rd I think there might be a few more bugs but can you fix the styles issue before I go back to fixing the bugs so I'll know if you need me to make some html code changes on the label plugin

here are the things that I need you to fix / change / improve

1. the css issues on the new version. I created demo checklist as we now have a lot of demo pages and hopefully this will reduce the clutter and disorganization of the demo files https://github.com/nutritionix/nutrition-label/blob/master/demo/demo.html.

   You need to edit the css file to make sure all 2018 demo pages look great https://github.com/nutritionix/nutrition-label/blob/master/nutritionLabel.css. You might need my assistance on some of the cases so just fix everything that you can.

   The 2018 demo pages are almost identical to the legacy version (hopefully this will make sense to you when you open the demo page `http://localhost/mattsilv/nutrition-label/demo/demo.html`). You can use the legacy version as a guide (if needed).

   all demo pages (legacy and 2018) uses this file (not the minified version) https://github.com/nutritionix/nutrition-label/blob/master/nutritionLabel.css so you just need a hard refresh after making a change on that file.

2. improve the demo page to make it more presentable or look like the main html page https://github.com/nutritionix/nutrition-label/blob/master/index.html (for consistency)

please take note that there are still a few issues but I thought it's best if we fix the style first before we compile the final list of bugs that needs to be fixed

let me know if you have any questions

thanks

**Comment by majin22** [comment]
@mattsilv am I correct to assume that for Potassium and Vitamin D, the rounding rule that we use for Vitamin A, Vitamin C, Calcium and Iron are the same rounding rule we will apply to these 2 values?

thanks

**Comment by mattsilv** [comment]
yes, let's use same rounding rule for potassium and vitamin D as vitamin
A/C  will update you if that changes.

**Comment by majin22** [comment]
@genesis23rd I didn't realize that one of my last minute changes caused problems with this https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-283861980. I will fix it first before I work on the changes that you need. thanks

**Comment by majin22** [comment]
this bug should now be fixed https://github.com/nutritionix/nutrition-label/issues/59#issuecomment-286567651

**Comment by majin22** [comment]
@Yurko-Fedoriv the final release is currently being tested but I believe you can start trying it out https://github.com/mattsilvllc/Nutritionix-Yii/issues/2778

you only need to add on the config `'showLegacyVersion' : false` to switch to the 2018 version

the new fields are listed on the changelog https://github.com/nutritionix/nutrition-label/blob/master/changelog.txt

let me know if you have any questions

thanks
