### ISSUE TITLE
create a wiki to note all the difference between the legacy and 2018 label

### ISSUE THREAD

**Issue by majin22** [nutritionix/nutrition-label#63]

**Comment by Yurko-Fedoriv** [comment]
@majin22 Vitamin A and C are not shown on 2018 version. Is this an expected behavior?

**Comment by majin22** [comment]
@Yurko-Fedoriv yes, that's correct, here's more info on the new version https://github.com/mattsilvllc/Nutritionix-Yii/wiki/New-Nutrition-Fact-Attributes-added-in-2017. thanks

**Comment by Yurko-Fedoriv** [comment]
@majin22 found this

> 8. Why are you no longer requiring vitamins A and C?
In the early 1990’s, American diets lacked Vitamins A and C, but now Vitamins A and C deficiencies in the general population are rare. Manufacturers are still able to list these vitamins voluntarily.

thanks, this answers my question

**Comment by majin22** [comment]
https://github.com/mattsilvllc/Nutritionix-Yii/wiki/Difference-Between-the-Legacy-and-the-2018-Label
