### ISSUE TITLE
Add special class to item name when there is no quantity textbox

### ISSUE THREAD

**Issue by genesis23rd** [nutritionix/nutrition-label#66]
![image](https://cloud.githubusercontent.com/assets/396910/23882994/373819dc-089f-11e7-9d75-5e448b16f08d.png)

**Comment by majin22** [comment]
related to #59

**Comment by majin22** [comment]
@genesis23rd the class is `nf-noQuantityTextbox`. I will pass task #59 again to you after I am done with all the changes. Thanks
