### ISSUE TITLE
Serving size unit scrolls down along with the item name.

### ISSUE THREAD

**Issue by majin22** [nutritionix/nutrition-label#67]
reported here https://github.com/mattsilvllc/Nutritionix-Yii/issues/2786#issuecomment-298492099

Not sure if this one is a bug.

`Serving size unit` scrolls down along with the item name.

http://dev2.nutritionix.com/label/item/217777
http://dev2.nutritionix.com/label_small/item/217777
http://dev2.nutritionix.com/label/ingredient/34868
http://dev2.nutritionix.com/label_small/ingredient/34868

Video: http://youtu.be/LJCuMR13eFw?hd=1

**Comment by majin22** [comment]
@genesis23rd can you pull the latest changes and check the demo `demo/2018-version/task-67.html`. Can you modify the design so we can solve issues like this. I understand that it might be tricky as the current design is already complex so we can accommodate all types of label.

Let me know if I can be of assistance in any way.

Thanks

**Comment by majin22** [comment]
@genesis23rd about this, I'll also try if I can solve it using javascript. thanks

**Comment by majin22** [comment]
@genesis23rd I might have a solution for this. I'll take over this task for now. thanks

**Comment by majin22** [comment]
@genesis23rd please pull the latest code and check the demos below and focus on example 7 and 8. they are identical to the labels above
* `/demo/2018-version/demo-long-item-name.html`
* `/demo/legacy-version/demo-long-item-name.html`

you will see that I have fixed the scroll on the 2018 version but the scrolling isn't smooth and have extra texts showing at the bottom (compare it with the legacy version)

i have set the demo files to use the non-minified version so we can easily test our changes while we work on this task

if you need to debug the scroll code, you can play with the js file, look for `xxx` and play with 2018 setting `scrollLongItemNamePixel` https://github.com/nutritionix/nutrition-label/blob/master/nutritionLabel.js#L566 (try 32 for the value, it will hide the extra text at the bottom but the scroll is still not smooth). just do a hard refresh on the demo file and your change should take effect.

things that might work for us if this can't be fixed by purely css changes
* have the 2018 version it's own `scrollLongItemNamePixel` setting (eg. `scrollLongItemNamePixel2018`)
* maybe some css fix / hack to work with the 2018 `scrollLongItemNamePixel` value
* if needed, changes on the html code

let me know if we need to discuss this via chat

thanks

**Comment by genesis23rd** [comment]
@majin22 I just updated the js file. 32px height is what we need for long item name for 2018 version.

**Comment by majin22** [comment]
@genesis23rd thanks. I'll just set 2 different settings for the long names. one for the legacy and another one for the 2018 version.

thanks
