### ISSUE TITLE
Regression: userFunctionNameOnQuantityChange can't be passed as function anymore

### ISSUE THREAD

**Issue by Yurko-Fedoriv** [nutritionix/nutrition-label#68]
Hello @majin22 
Can you please tell why have you removed this feature which I added earlier: https://github.com/nutritionix/nutrition-label/commit/fcb344c885688be81fd19dfaa40fce7d30fd6c50#diff-9ce72bf5eb39b381c67a00ed3b790dd5R723

https://github.com/nutritionix/nutrition-label/commit/1519dcd360939cb0488866662286ce3f0e97e639#diff-9ce72bf5eb39b381c67a00ed3b790dd5R769

I use this feature in angular integration, and I'm missing it trying to update to the latest label version. You could support both variants (based on the param string/function type), but honestly passing such handlers by global function name isn't something I would advocate.

**Comment by majin22** [comment]
@Yurko-Fedoriv i came across this bug when working on the 2018 label version #64

I wasn't aware you made that change but it broke that feature when the label is used on a normal browser

feel free to make the change again and let me know when you're done so I can test it

thanks

**Comment by Yurko-Fedoriv** [comment]
@majin22 please check out relevant PR https://github.com/nutritionix/nutrition-label/pull/69

**Comment by majin22** [comment]
reviewed and merged

**Comment by majin22** [comment]
@Yurko-Fedoriv a new version has been released and will be tested on dev2 asap https://github.com/nutritionix/nutrition-label/releases.

let me know if there are any issues

thanks

**Comment by Yurko-Fedoriv** [comment]
@majin22 thank you
