### ISSUE TITLE
Option for not doing calculations

### ISSUE THREAD

**Issue by JCapriotti** [nutritionix/nutrition-label#72]
I am wondering if there is a way to disable calculations done inside the widget (e.g. for % daily value), and instead only display values provided to the label widget? Or if not, would this be a useful feature?

We may have a need for this, so may work on it at some point.

Thanks,
Jason

**Comment by majin22** [comment]
@JCapriotti currently, we don't have that feature but you can simply hide the arrows and then add a small javascript code to prevent the changes on the textbox being triggered (I haven't tried it though) http://dev2.nutritionix.com/html/label-jquery-plugin/demo/legacy-version/demo.html#test17

good luck
