### ISSUE TITLE
minor design issue on the legacy label --- changed to: new setting: legacyVersion

### ISSUE THREAD

**Issue by majin22** [nutritionix/nutrition-label#77]
see https://github.com/mattsilvllc/NewSiteDesign/issues/1521 (more details to follow later)

**Comment by majin22** [comment]
the final decision for cases like this is to implement a version feature (probably in the setting) so the old design and the new one can be used without any issue

there no final idea yet on how this will be implemented

**Comment by majin22** [comment]
**from @genesis23rd, posted on a private repo**

@majin22 After playing around with this issue, we need to update the serving markup with the following changes:

from: (**this will be for `legacyVersion: 1`**)
```
<div class="servingUnit fl unitHasTextbox">
  pack (as consumed)
</div>
<div class="servingWeightGrams fl gramsHasTextbox">
  (<span itemprop="servingSize">171g</span>)
</div>
```
to:  (**this will be for `legacyVersion: 2`**)
```
<div class="servingUnit fl unitHasTextbox">
  pack (as consumed)
  <span class="servingWeightGrams gramsHasTextbox">
    (<span itemprop="servingSize">171g</span>)
  </span>
</div>
```
![image](https://user-images.githubusercontent.com/396910/28861926-b9da2b5e-7795-11e7-9e79-c9d368f773fd.png)


Let's chat on gchat about this. Thanks

**Comment by majin22** [comment]
the issue here is linked to the width of the label. I am just adding this info as I found out about it while running some tests

![legacy version demo page](https://user-images.githubusercontent.com/271582/29485568-6136f7a6-8506-11e7-87b7-9313b84ddabd.png)

**Comment by majin22** [comment]
@mattsilv do you the QAs to ran tests similar to this for the 2018 version in case we need to add a `version feature` to it too?

thanks

**Comment by majin22** [comment]
@genesis23rd can you pull the latest code and check out examples 2 and 4 on `http://localhost/mattsilv/nutrition-label/demo/legacy-version/demo-legacy-version-1-feature.html` because the design is off but I think the html code is correct. thanks

**Comment by majin22** [comment]
@genesis23rd in case you need to ran some css tests, you can change `nutritionLabel.css` and it should affect the `demo-legacy-version-1-feature.html` demo page. thanks

**Comment by mattsilv** [comment]
anything specific for me to check on this?

**Comment by majin22** [comment]
@mattsilv not yet but I expect to finalize this soon. thanks

**Comment by majin22** [comment]
@mattsilv I am sorry, I thought this was for the image label. I have a question for you https://github.com/nutritionix/nutrition-label/issues/77#issuecomment-323513251 because I found out that the issue is caused by wider labels https://github.com/nutritionix/nutrition-label/issues/77#issuecomment-323513206

> @mattsilv do you the QAs to ran tests similar to this for the 2018 version in case we need to add a version feature to it too?

> thanks

**Comment by majin22** [comment]
@genesis23rd I want to bump this task https://github.com/nutritionix/nutrition-label/issues/77#issuecomment-323540376. thanks

**Comment by genesis23rd** [comment]
@majin22
```
<div class="servingUnit fl unitHasTextbox">
    wingette or drummette			
    <span class="servingWeightGrams fl gramsHasTextbox">
        (<span itemprop="servingSize">27g</span>)
    </span>
</div>
```
Please remove the "fl" class from this line:
```
<span class="servingWeightGrams fl gramsHasTextbox">
```

**Comment by majin22** [comment]
@genesis23rd can you pull the latest file and check out the demo `http://localhost/mattsilv/nutrition-label/demo/legacy-version/demo-legacy-version-feature.html`

the `version 2` demo looks a bit weird compared to the other text (examples with `B` and `D`)

the demo is using the non minified css `nutritionLabel.css` so you can ran some test if you need to

let me know if I need to make some html changes to the `version 2` labels

thanks

**Comment by genesis23rd** [comment]
@majin22 I did some margin and padding adjustments.

**Comment by Pzykoh** [comment]
Found a bug when testing #2950 

Some of the serving size text boxes are touching the black bar design on the label.

Here are some screenshots of the issue: 

![image](https://user-images.githubusercontent.com/12953122/29678607-c55c9fea-8931-11e7-8f17-d9febe7da73d.png)

![image](https://user-images.githubusercontent.com/12953122/29678723-30f67e42-8932-11e7-8560-11ca6e740aa8.png)

**Comment by majin22** [comment]
@mattsilv please disregard my question https://github.com/nutritionix/nutrition-label/issues/77#issuecomment-324074007

I was thinking about it and I believe I have a better solution of knowing if there is a similar issue for the 2018 version of the label

i just prefer to wait until this task is completed before I check it in case some of the changes here affects the 2018 version too (which might make the test not reliable after this issue is complete)

thanks

**Comment by ninogarcia** [comment]
Same issue with https://github.com/nutritionix/nutrition-label/issues/77#issuecomment-324698028 but on mobile version.

http://dev2.nutritionix.com/html/label-jquery-plugin/demo/legacy-version/demo-mobile.html 
Example 1

![1](https://user-images.githubusercontent.com/7455410/29696522-198c4832-897c-11e7-86f4-d454f60650c8.png)

**Comment by Pzykoh** [comment]
I think some of the labels [here](http://dev2.nutritionix.com/html/label-jquery-plugin/demo/legacy-version/demo-legacy-version-feature.html) can be improved in the design.

Here's the specific labels:

- http://dev2.nutritionix.com/html/label-jquery-plugin/demo/legacy-version/demo-legacy-version-feature.html
- http://dev2.nutritionix.com/html/label-jquery-plugin/demo/legacy-version/demo-legacy-version-feature.html#test5
- http://dev2.nutritionix.com/html/label-jquery-plugin/demo/legacy-version/demo-legacy-version-feature.html#test7
- http://dev2.nutritionix.com/html/label-jquery-plugin/demo/legacy-version/demo-legacy-version-feature.html#test11

**Comment by majin22** [comment]
@Pzykoh can check the labels you are pointing out again. the reason why you might think they need improvement is because they don't have the setting `'legacyVersion' : 2`. the purpose of the demo is to show the difference of the labels when they have different settings

message me if you need some clarification.

thanks

**Comment by Pzykoh** [comment]
@majin22 

Got it. Thanks for the clarification.

**Comment by majin22** [comment]
@mattsilv @genesis23rd @Yurko-Fedoriv @Pzykoh and @ninogarcia I just want to let you know that this issue don't exist on the 2018 version (maybe a few minor css improvements but we can deal with that later if needed)

Here is an image of the resulting test page with the same data as the one here http://dev2.nutritionix.com/html/label-jquery-plugin/demo/legacy-version/demo.html

![2018 version demo page](https://user-images.githubusercontent.com/271582/29754903-83436ee4-8bc1-11e7-83b1-05022988a1a3.png)

**Comment by Yurko-Fedoriv** [comment]
@majin22 not true, 2018 version has the same issue

http://dev2.nutritionix.com/html/label-jquery-plugin/demo/2018-version/demo-long-item-name.html

![image](https://user-images.githubusercontent.com/1327761/29761490-fdc6b8c8-8bd1-11e7-9734-6af47f104031.png)

I think it's mostly specific to how mac renders default scrolls (it does not).

**Comment by majin22** [comment]
@Yurko-Fedoriv I am sorry for the confusion, I was referring to the design issue where some of the texts aren't displayed properly (see the internal discussion here https://github.com/mattsilvllc/NewSiteDesign/issues/1521#issuecomment-324690941) and not the scroll problem

the scroll problem is currently being investigated by @genesis23rd 

but thanks for checking it oout

**Comment by Yurko-Fedoriv** [comment]
@majin22 thanks for the clarification

**Comment by genesis23rd** [comment]
@majin22 @Pzykoh This https://github.com/nutritionix/nutrition-label/issues/77#issuecomment-324698028 is fixed

**Comment by majin22** [comment]
passing this back to @genesis23rd after discussing some spacing issue
