### ISSUE TITLE
long item name scroll feature isn't appearing on most browsers

### ISSUE THREAD

**Issue by majin22** [nutritionix/nutrition-label#79]
internal discussion started here https://github.com/mattsilvllc/NewSiteDesign/issues/1521#issuecomment-324675446

***

screenshot from @Yurko-Fedoriv 

> ![image](https://user-images.githubusercontent.com/1327761/29677895-432b6bcc-8905-11e7-9813-ecec7d233b20.png)

***

another reply from @Yurko-Fedoriv 

> ![image](https://user-images.githubusercontent.com/1327761/29687131-03238ce8-8924-11e7-9f8a-7b4d48a11163.png)

> ![image](https://user-images.githubusercontent.com/1327761/29687143-0b0c422e-8924-11e7-8ac3-4c71f9939b42.png)

> just to be clear, it does scroll, it's just there is no visible indication that it can be scrolled.

***

from @pzykoh

> The scroll is missing on the following:
> - Mozilla Firefox (54.0.1) - 2018 version only
> - Safari (10.1) [Sierra OS] - Both Legacy and 2018 version
> - Safari (Ipad Pro, ios 10.3) - Both Legacy and 2018 version

**Comment by majin22** [comment]
@genesis23rd I did some research and this might help us solve the issue https://stackoverflow.com/questions/40262509/overflow-scrollbar-not-showing-on-100-height-div-in-firefox

you know css better than me so I'll leave it up to you to make the change

thanks

**Comment by majin22** [comment]
reopening this as QAs found that there are still some issues

**Comment by majin22** [comment]
just a note that this issue is still present on firefox based on our QAs test

**Comment by majin22** [comment]
@Pzykoh can you test this again and see if this is still an issue with the latest version of the browsers. thanks

**Comment by Pzykoh** [comment]
@majin22 This is not anymore an issue on the current supported browsers. thanks.
