### ISSUE TITLE
publish to npm with package.json

### ISSUE THREAD

**Issue by AndersDJohnson** [nutritionix/nutrition-label#87]
Would you consider publishing this to npm for consumers from tools like Webpack? Should just need to add a `package.json` and maybe an `.npmignore` if you wish.

**Comment by majin22** [comment]
@Yurko-Fedoriv what do you think about this idea? thanks

**Comment by Yurko-Fedoriv** [comment]
@majin22 this is modern thing to do. We potentially will benefit from it too.

**Comment by majin22** [comment]
noted. i'll add this to my todo list. this probably won't take too long once I know how to do it as we already published the plugin on bower. thanks

**Comment by majin22** [comment]
@AndersDJohnson here you go https://www.npmjs.com/package/nutrition-label-jquery-plugin. thanks
