### ISSUE TITLE
Feature: additional voluntary nutrients

### ISSUE THREAD

**Issue by drdogbot7** [nutritionix/nutrition-label#88]
It would be nice to have the option to add additional "voluntary" nutrients (Vitamin K, Magnesium, etc), that are allowed but not required on a label.

**Comment by majin22** [comment]
I will forward this to our team for approval but I don't think this is something that we can add for now. Thanks

**Comment by majin22** [comment]
@drdogbot7 I just want to let you know that even though this will be a nice feature, we can't spend time developing it. thanks
