### ISSUE TITLE
angular / typescript support?

### ISSUE THREAD

**Issue by chriseugenerodriguez** [nutritionix/nutrition-label#92]
anyone know how to implement this for angular or typescript

**Comment by majin22** [comment]
@Yurko-Fedoriv i'm tagging you in case you can help out here. thanks

**Comment by chriseugenerodriguez** [comment]
i was able to install jquery in typescript project, and added project as a typing for it, but nothing outputs.

**Comment by majin22** [comment]
i am sorry but i have no experience with typescript so I can't help you out.

**Comment by chriseugenerodriguez** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by majin22** [comment]
@Yurko-Fedoriv can you check this out in case you can help here. thanks

**Comment by Yurko-Fedoriv** [comment]
@chriseugenerodriguez can you point to some boilerplate which is similar to your environment, so we better see what are your requirements

**Comment by majin22** [comment]
@chriseugenerodriguez just tagging you in case you didn't get the notice earlier because the task was closed. thanks

@Yurko-Fedoriv thanks for this

**Comment by chriseugenerodriguez** [comment]
Its angular cli.

**Comment by majin22** [comment]
@Yurko-Fedoriv just bumping this. thanks

**Comment by majin22** [comment]
@Yurko-Fedoriv just bumping this. thanks

**Comment by majin22** [comment]
@chriseugenerodriguez I am sorry that I forgot that @Yurko-Fedoriv was on vacation for a few more days.

can you post a snippet of your code and any console error so we can try and find out why this isn't working for you

thanks
