### ISSUE TITLE
Demos use media='screen' vs media='all'   - printing labels from demo doesn't work

### ISSUE THREAD

**Issue by sdwarwick** [nutritionix/nutrition-label#96]
all of the "demo" files use 
`   <link rel='stylesheet' type='text/css' media='screen' href='../nutritionLabel-min.css'>`
to include the css.

This means that if someone tries to print a label, they only get the unformatted text.  

Suggestion is to update all of the demo files to use `media='all'`

**Comment by majin22** [comment]
thanks for this suggestion. i'll add this to my todo list

cc @mattsilv
