### ISSUE TITLE
Horizontal layouts

### ISSUE THREAD

**Issue by sdwarwick** [nutritionix/nutrition-label#98]
FDA specification calls out a number of horizontal formats. It would be nice to have those supported as well.

**Comment by majin22** [comment]
i am sorry but we don't have any plans on implementing something like this

cc @mattsilv in case he wants to consider this feature as a low priority task

**Comment by sdwarwick** [comment]
I have forked this project and plan to continue development. I have merged the very helpful additions by @drdogbot7

**Comment by majin22** [comment]
thanks for this notice. i was too busy with other projects that I missed the forks. I will check them out later
